#!/bin/bash

# This is a shell script that serves to run all of the stuff needed for pdf2txt

# identify the file path that will ultimately host the program
RUNPATH=/home/$USER/Packages/pdf2txt_venv_gui/PDF2TXT/pdf2txt


# verify internet connection before attempting to update or install

# check if the directory already exists
if [ -d "/home/$USER/Packages/pdf2txt_venv_gui/" ]; then
	echo "PDF2TXT already installed."
	
	# this logic handles updating the dependencies. It will not run if there is no internet connection
	if [ connection_check ]; then
		echo "Checking for Updates."
		echo ""
		pip3 install farm-haystack -U >& /dev/null	
	else
		echo "No internet connection, skipping updates."
	fi
	
	cd /home/$USER/Packages/pdf2txt_venv_gui
	source bin/activate

# if it doesn't exist, we need to make it and install all the stuff we need
else
	echo "PDF2TXT has not been installed."
	echo ""
	
	#this logic makes sure we have an internet connection. If we don't, it warns the user and exits the program
	if [ connection_check ]; then
		mkdir /home/$USER/Packages/pdf2txt_venv_gui/
		python3 -m venv /home/$USER/Packages/pdf2txt_venv_gui/
		cd /home/$USER/Packages/pdf2txt_venv_gui
	
		# the installation of the dependencies and whatnot are done within the virtual environment we just built
		source bin/activate
		git clone https://github.com/NLPatVCU/PDF2TXT.git
		pip3 install farm-haystack
		deactivate
	else
		echo "You are not connected to the internet (or Google is down and the check failed). Exiting install"
		exit
	fi
fi
	
# at this point we are ready to actually take the arguments and run pdf2txt

# get the arguments to pass to PDF2TXT

# get the wholefile argument
wholefile=O
while [ "$wholefile" != "Y" ] && [ "$wholefile" != "N" ]; do
	echo "Convert whole directory? (Y/N)"
	read input1
	wholefile=$input1
done

echo""

# get the input filepath and output filepath arguments
echo "Input the COMPLETE input and output file paths separated by a space."
read infile outfile

# we can now actually run pdf2txt
source bin/activate
cd $RUNPATH
if [ $wholefile = "N" ]; then
	python3 pdf2txt.py -f $infile -o $outfile
else
	python3 pdf2txt.py -d $infile -o $outfile
fi
echo ""
echo "conversion complete. converted files located at $outfile"



# this function checks for internet connection
connection_check() {
	ping_result=$(ping -c 1 -q google.com >&/dev/null) # check for connection by pinging google, return true if the ping works
	if [ $ping_result != 0 ]; then
		return true
	else
		return false
	fi
		
}
